[profile.default]
src = "contracts"
out = "artifacts_forge"
libs = ["lib"]
test = "test_forge"
cache_path = "cache_forge"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]

verbosity = 3
viaIR = true

[lint]
exclude_lints = [
    "asm-keccak256",
    "mixed-case-function",
    "unwrapped-modifier-logic",
]
