[profile.default]
src = "contracts"
out = "artifacts_forge"
libs = ["lib"]
test = "test_forge"
cache_path = "cache_forge"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]

verbosity = 3
viaIR = true

fs_permissions = [
    { access = "read", path = "./test/data" },
    { access = "read-write", path = "./output" }
]

[lint]
exclude_lints = [
    "asm-keccak256",
    "mixed-case-function",
    "unwrapped-modifier-logic",
]

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY_SEPOLIA}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[invariant]
runs = 256              # Количество runs для fuzzing
depth = 50              # Глубина вызовов за один run